# Generated by Django 5.1.5 on 2026-01-29 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
        ("people", "0005_member_whatsapp_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="member",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="staff_account",
                to="people.member",
            ),
        ),
    ]
