# Generated by Django 5.1.5 on 2026-01-24 17:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ministry", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SmallGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("semester", models.CharField(max_length=50)),
                (
                    "leader_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("status", models.CharField(default="active", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
