# Generated by Django 6.0.1 on 2026-01-31 20:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_user_member"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="registration_type",
            field=models.CharField(
                choices=[
                    ("first_timer", "First Timer"),
                    ("worker", "Worker"),
                    ("member", "Member"),
                ],
                default="member",
                max_length=20,
            ),
        ),
    ]
