# Generated by Django 5.1.5 on 2026-01-25 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0003_member_baptism_date_member_bio_member_city_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Family",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("address", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="member",
            name="family_role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Head", "Head"),
                    ("Spouse", "Spouse"),
                    ("Child", "Child"),
                    ("Relative", "Relative"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="family",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="members",
                to="people.family",
            ),
        ),
    ]
