# Generated by Django 5.1.5 on 2026-01-29 22:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0004_family_member_family_role_member_family"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="whatsapp_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
