# Generated by Django 5.1.5 on 2026-01-29 22:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("outreach", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="visitor",
            name="whatsapp_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
