# Generated by Django 5.1.5 on 2026-01-29 23:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("outreach", "0002_visitor_whatsapp_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visitor",
            name="visit_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
