# Generated by Django 5.1.5 on 2026-01-25 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ministry", "0002_smallgroup"),
        ("people", "0002_alter_member_member_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="ministry",
            name="active_participation_rate",
            field=models.IntegerField(default=0, help_text="Percentage 0-100"),
        ),
        migrations.AddField(
            model_name="ministry",
            name="icon_type",
            field=models.CharField(
                default="users", help_text="Lucide icon name", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="ministry",
            name="last_report_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ministry",
            name="meeting_day",
            field=models.CharField(
                blank=True,
                choices=[
                    ("monday", "Monday"),
                    ("tuesday", "Tuesday"),
                    ("wednesday", "Wednesday"),
                    ("thursday", "Thursday"),
                    ("friday", "Friday"),
                    ("saturday", "Saturday"),
                    ("sunday", "Sunday"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="ministry",
            name="reporting_status",
            field=models.CharField(
                choices=[
                    ("up_to_date", "Up to date"),
                    ("pending", "Pending"),
                    ("overdue", "Overdue"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="ministry",
            name="team_lead",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="led_ministries",
                to="people.member",
            ),
        ),
    ]
