# Generated by Django 5.1.5 on 2026-01-25 04:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="member_type",
            field=models.CharField(
                choices=[
                    ("Member", "Member"),
                    ("Guest", "Guest"),
                    ("Worker", "Worker"),
                    ("New Convert", "New Convert"),
                ],
                default="Member",
                max_length=50,
            ),
        ),
    ]
