# Generated by Django 5.1.5 on 2026-01-25 07:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0002_alter_member_member_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="baptism_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="member",
            name="bio",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="member",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="member",
            name="emergency_contact_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="member",
            name="emergency_contact_phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="member",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("Male", "Male"), ("Female", "Female")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="marital_status",
            field=models.CharField(
                blank=True,
                choices=[("Single", "Single"), ("Married", "Married")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="occupation",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="member",
            name="postal_code",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="member",
            name="salvation_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
