# Generated by Django 5.1.5 on 2026-01-25 07:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("operations", "0005_attendance_adult_count_attendance_children_count"),
    ]

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("publication_date", models.DateField(auto_now_add=True)),
                ("is_public", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
