# Generated by Django 5.1.5 on 2026-01-25 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("operations", "0002_communityimpact"),
        ("people", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="finance",
            name="member",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="people.member",
            ),
        ),
    ]
