# Generated by Django 5.1.5 on 2026-01-25 04:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("operations", "0004_expense"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="adult_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="attendance",
            name="children_count",
            field=models.IntegerField(default=0),
        ),
    ]
