# Generated by Django 5.1.5 on 2026-01-25 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ministry", "0004_service"),
        ("operations", "0006_announcement"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ministry.service",
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="service_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
